Made tango configure to check build system ImageMagick

diff --git a/patch/tango_pkg_config_host.patch b/patch/tango_pkg_config_host.patch
--- a/patch/tango_pkg_config_host.patch
+++ b/patch/tango_pkg_config_host.patch
@@ -1,6 +1,6 @@
 diff -Nurd tango-icon-theme-0.8.90/configure tango-icon-theme-0.8.90/configure
---- tango-icon-theme-0.8.90/configure	2009-02-26 05:08:00.000000000 +0200
-+++ tango-icon-theme-0.8.90/configure	2015-10-09 00:22:33.709364842 +0300
+--- tango-icon-theme-0.8.90/configure	2015-10-16 19:58:33.255795468 +0300
++++ tango-icon-theme-0.8.90/configure	2015-10-16 19:57:00.974783757 +0300
 @@ -6410,9 +6410,9 @@
  
  { echo "$as_me:$LINENO: checking icon-naming-utils >= $UTILS_REQUIRED" >&5
@@ -23,3 +23,40 @@ diff -Nurd tango-icon-theme-0.8.90/configure tango-icon-theme-0.8.90/configure
     ICONMAP="$UTILS_PATH/icon-name-mapping"
  
     { echo "$as_me:$LINENO: result: yes" >&5
+@@ -6454,17 +6454,17 @@
+ 
+ 
+ if test "x$enable_framing" = "xyes"; then
+-   if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"ImageMagick >= 5.5.7\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "ImageMagick >= 5.5.7") 2>&5
++   if test -n "$PKG_CONFIG_FOR_BUILD" && \
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG_FOR_BUILD --exists --print-errors \"ImageMagick >= 5.5.7\"") >&5
++  ($PKG_CONFIG_FOR_BUILD --exists --print-errors "ImageMagick >= 5.5.7") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+   enable_framing=yes
+ else
+-  if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"GraphicsMagick >= 1.1\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "GraphicsMagick >= 1.1") 2>&5
++  if test -n "$PKG_CONFIG_FOR_BUILD" && \
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG_FOR_BUILD --exists --print-errors \"GraphicsMagick >= 1.1\"") >&5
++  ($PKG_CONFIG_FOR_BUILD --exists --print-errors "GraphicsMagick >= 1.1") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+@@ -6543,9 +6543,9 @@
+ { echo "$as_me:$LINENO: checking SVG to PNG conversion method" >&5
+ echo $ECHO_N "checking SVG to PNG conversion method... $ECHO_C" >&6; }
+ if test "x$enable_large_bitmaps" = "xyes"; then
+-   if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"librsvg-2.0 >= 2.12.3\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "librsvg-2.0 >= 2.12.3") 2>&5
++   if test -n "$PKG_CONFIG_FOR_BUILD" && \
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG_FOR_BUILD --exists --print-errors \"librsvg-2.0 >= 2.12.3\"") >&5
++  ($PKG_CONFIG_FOR_BUILD --exists --print-errors "librsvg-2.0 >= 2.12.3") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
